name: gp_partner_app
description: GP Partner mobile app for specialists and shops.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  gp_mobile_shared:
    path: ../gp_mobile_shared
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

