/** Auto-moderation rule identifiers */
export const AUTO_MODERATION_RULES = {
  AUTO_COMPLAINT_LIMIT_24H: 'AUTO_COMPLAINT_LIMIT',
  AUTO_COMPLAINT_LIMIT_7D: 'AUTO_COMPLAINT_LIMIT_7D',
  AUTO_SUSPICIOUS_ACTIVITY: 'AUTO_SUSPICIOUS_ACTIVITY',
  AUTO_PAYMENT_DEBT: 'AUTO_PAYMENT_DEBT',
  AUTO_DOCUMENT_EXPIRED: 'AUTO_DOCUMENT_EXPIRED',
  AUTO_MULTIPLE_FAKE_ACCOUNTS: 'AUTO_MULTIPLE_FAKE_ACCOUNTS',
  AUTO_REPEAT_SUSPENSIONS: 'AUTO_REPEAT_SUSPENSIONS',
  AUTO_FRAUD_DETECTED: 'AUTO_FRAUD_DETECTED',
} as const;

export type AutoModerationRuleId =
  (typeof AUTO_MODERATION_RULES)[keyof typeof AUTO_MODERATION_RULES];

export const AUTO_MODERATION_THRESHOLDS = {
  complaints24h: 3,
  complaints7d: 5,
  orders1h: 15,
  suspensions30d: 3,
};
