import { GP_INTERNAL_EXECUTOR_ID, GP_INTERNAL_EXECUTOR_NAME } from '../constants/furnitureExecutor.js'

export function buildFurnitureExecutorSeed() {
  const now = Date.now()
  return [
    {
      id: 'feo-demo-mfg',
      serviceType: 'furniture_manufacturing',
      serviceProjectId: null,
      clientName: 'Айдар Клиент',
      phone: '+77001110001',
      address: 'ул. Сейфуллина 12, Уральск',
      comment: 'Кухня 2.4 м · ЛДСП белый',
      city: 'Уральск',
      status: 'new',
      assignedPartnerId: null,
      executorInternal: true,
      executorLabel: GP_INTERNAL_EXECUTOR_NAME,
      internalExecutorId: GP_INTERNAL_EXECUTOR_ID,
      totalPrice: 116000,
      gpCommission: 13920,
      franchiseId: 'fr-uralsk',
      createdAt: now - 3600000,
      updatedAt: now - 3600000,
    },
    {
      id: 'feo-demo-asm',
      serviceType: 'furniture_assembly',
      serviceProjectId: null,
      clientName: 'Серик Атырау',
      phone: '+77002220002',
      address: 'мкр. Атырау-1',
      comment: 'Сборка шкафа IKEA',
      city: 'Атырау',
      status: 'new',
      assignedPartnerId: null,
      executorInternal: true,
      executorLabel: GP_INTERNAL_EXECUTOR_NAME,
      internalExecutorId: GP_INTERNAL_EXECUTOR_ID,
      totalPrice: 15000,
      gpCommission: 1800,
      franchiseId: 'fr-uralsk',
      createdAt: now - 7200000,
      updatedAt: now - 7200000,
    },
    {
      id: 'feo-demo-rep',
      serviceType: 'furniture_repair',
      serviceProjectId: null,
      clientName: 'Айдар Клиент',
      phone: '+77001110001',
      address: 'ул. Абая 5',
      comment: 'Замена фасада',
      city: 'Уральск',
      status: 'accepted',
      assignedPartnerId: 'p1',
      executorInternal: false,
      executorLabel: null,
      internalExecutorId: null,
      totalPrice: 12000,
      gpCommission: 1440,
      franchiseId: 'fr-uralsk',
      createdAt: now - 86400000,
      updatedAt: now - 3600000,
    },
  ]
}
