ALTER TABLE "PartnerProfile" ADD COLUMN IF NOT EXISTS "completedOrders" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PartnerProfile" ADD COLUMN IF NOT EXISTS "canceledOrders" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PartnerProfile" ADD COLUMN IF NOT EXISTS "rating" DOUBLE PRECISION NOT NULL DEFAULT 5;
