-- CreateEnum
CREATE TYPE "LawnWorkType" AS ENUM ('MOWING', 'CARE', 'CLEANUP');

-- AlterEnum
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'STARTED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'CLIENT_CONFIRMED';

-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "preferredDate" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "preferredTime" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "flexibleTime" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "lawnAreaSqm" INTEGER;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "lawnWorkType" "LawnWorkType";
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "clientConfirmedAt" TIMESTAMP(3);
